<a href="https://colab.research.google.com/github/subhashhkumarr1116-stack/testing001/blob/main/0Day.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


In [ ]:
print("hello machine")

hello machine


In [ ]:
a = 10
print(a * 10)

100


In [ ]:
a = 5
b = 10
f = 20
d = 20
e = 25
print (a+b+f+d+e)

80


In [ ]:
a = int(input())
b = int(input())
c = int(input())
print(a+b+c)

10
10
10
30


In [ ]:
a = 10
b = 5
print(a+b+c)

25


In [ ]:
a = 5
b = 10
print( a,b)

temp = b
b = a
a = temp
print( a, b)

5 10
10 5


In [ ]:
a = 2
b = 3
print(a,b)
a = a + b
b = a - b
a = a - b
print(a,b)

2 3
3 2


In [ ]:
a = int(input(a<50))
for a in range(1,51):
 if(a%2==0):
  print(a)
  a+=1



KeyboardInterrupt: Interrupted by user

In [ ]:
a = int(input())

if a%2 == 0 :
  print("even")
else:
  print("odd")

100
even


In [ ]:
a = int(input())

if a > 0 :
  print("positive")
elif a == 0:
  print("zero")
else:
  print("negative")

0
zero


In [ ]:
a = input("mon")
if a == "sun":
  print("sunday")
elif a == "mon":
  print("monday")
elif a == "tues":
  print("tuesday")
elif a == "wednes":
  print("wednesday")
elif a == "thurs":
  print("thursday")
elif a == "fri":
  print("friday")
else:
  print("saturday")

monday


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(1,9,2): #(start,end,step)
  print(i)


1
3
5
7


In [ ]:
a = 0

while a < 10:
  print(a)
  a = a + 1

0
1
2
3
4
5
6
7
8
9


In [ ]:
a = input("Enter the word:")
b = len(a)
print(b)

Enter the word:abcdefghijklmnopqrstuvwxyz
26


In [ ]:
a = input("Enter the word: ")
b = len(a)
is_palindrome = True

for i in range(b // 2):
    if a[i] != a[b - 1 - i]:
        is_palindrome = False
        break

if is_palindrome:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter the word: racar
Palindrome


In [ ]:
a = input()
b =len(a)
is_palindrome = True

for i in range (b // 2):
  if a[i] != a[b-1-i]:
      is_palindrome = False
      break

if is_palindrome:
      print("palindrome")
else:
      print("not palindrome")

racer
not palindrome


In [ ]:
lst = [1, 2, 3, "Hello", 'c', [5, 6]]  #list
print(lst)

#append(only take one single value)
lst.append(9)
print(lst)

#extend()(can take more than 1 value)
lst.extend([5,6,8])
print(lst)

#insert(can add value at any index)
lst.insert(2, "value")
print(lst)

[1, 2, 3, 'Hello', 'c', [5, 6]]
[1, 2, 3, 'Hello', 'c', [5, 6], 9]
[1, 2, 3, 'Hello', 'c', [5, 6], 9, 5, 6, 8]
[1, 2, 'value', 3, 'Hello', 'c', [5, 6], 9, 5, 6, 8]


In [ ]:
lst = ['Prince', 22, 'Karachi']
print(lst)

lst.insert(1, "Mirai")
print(lst)

lst.append([732,222])
print(lst)

['Prince', 22, 'Karachi']
['Prince', 'Mirai', 22, 'Karachi']
['Prince', 'Mirai', 22, 'Karachi', [732, 222]]


In [ ]:
lst = [1, 11, 2, 3, 5, 7, 9, 9, 9]

#pop()(removes last element )
lst.pop()
print(lst)

#remove()

lst.remove(2)
print(lst)

#index()
#lst.index(2)
print(lst.index(5))

#count

print(lst.count(9))

#sort()
lst.sort()
print(lst)

# sum, min, max
print(sum(lst))
print(min(lst))
print(max(lst))
print(sorted(lst))



[1, 11, 2, 3, 5, 7, 9, 9]
[1, 11, 3, 5, 7, 9, 9]
3
2
[1, 3, 5, 7, 9, 9, 11]
45
1
11
[1, 3, 5, 7, 9, 9, 11]


In [ ]:
lst = [-9, 8, 11, -44, 50, 1, 0]

#lst.sort()
#print(lst)

print(sum(lst))
print(min(lst))
print(max(lst))

a = sorted(lst)
print(a)

17
-44
50
[-44, -9, 0, 1, 8, 11, 50]


In [ ]:
tp = (1, 4, 3, 2, 3)

a = tuple(sorted(tp))
print(a)

print(sum(tp))
print(tp.count(3))
print(tp.index(3))




#functions that can be used
# count(), index(), len(), sum(), max()/min(), sorted()(returns list)


(1, 2, 3, 3, 4)
13
2
2


In [ ]:
lst1 = [1,2,3]
lst2 = [4,5,6]
result = []

for i in range(len(lst1)):
    result.append(lst1[i] + lst2[i])

print(result)

[5, 7, 9]


In [ ]:
lst1 = []
lst2 = []

size = int(input())

3for i in range(size):
    x = int(input())

    lst1.append(x)

for j in range(size):
  y = int(input())

  lst2.append(y)

lst3 = []

for i in range(size):
  lst3.append(lst1[i] + lst2[j])

print(lst3)




3
1
2
3
3
1
2
[3, 4, 5]


In [ ]:
#Numpy

import numpy as np

# Example of checking data type
my_list = [1, 2, 3]
print(f"Type of my_list: {type(my_list)}")

my_string = "hello"
print(f"Type of my_string: {type(my_string)}")

# Using existing numpy arrays from the notebook state
# (Assuming 'a' and 'np_arr' are defined in subsequent cells)
# print(f"Type of variable 'a': {type(a)}")
# print(f"Data type of numpy array 'a': {a.dtype}")

# print(f"Type of variable 'np_arr': {type(np_arr)}")
# print(f"Data type of numpy array 'np_arr': {np_arr.dtype}")


In [ ]:
a = np.array([1, 2, 3, 9, 0, 2,'q', '3'])
print(a)

['1' '2' '3' '9' '0' '2' 'q' '3']


In [ ]:
np_arr = np.array([3,3,3,3,3.3, 'hello',False])
print(bool(np_arr[-1]))

a = False
print(bool(a))

True
False


In [ ]:
a = np.zeros((2,3,4) , dtype=int)
print(a)

print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [ ]:
a = np.empty(45 , dtype=int)
print(a)

#print(type(a[0][0][0]))

[      311352582               0       312548144 138605571333680
               0               0               0               0
               0               0               0               0
               0               0               0               0
               0               0               0               0
               0               0               0               0
               0               0               0               0
               0               0               0             113
       311641792 138605571333440               0               0
               0               0               0               0
               0               0               0               0
            1008]


In [ ]:
a = np.full(4,5 , dtype=int)
print(a)



[5 5 5 5]


In [ ]:
a = np.arange(99,199,10, dtype=int) #(starting,ending,jump)
print(a)



[ 99 109 119 129 139 149 159 169 179 189]


In [ ]:
a = np.linspace(4 ,16, 3, dtype = int)
print(a)



[ 4 10 16]


In [ ]:
a = np.zeros((2,3,5), dtype=int)
print(a.shape)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2105990620.py, line 1)

In [ ]:

a = np.random.randint(1,100,10)
print(a)



[31 84 99 94 57 91 81 39 82 19]


In [ ]:
a = np.random.choice([2,4,5,9,11,22], 2)
print(a)

[22  5]


In [ ]:


# A 1D array of shape (3,)
arr = np.array([1, 2, 3])

# Broadcasting happens here: 10 is treated like [10, 10, 10]
result = arr + 10

print(result)
# Output: [11, 12, 13]

[11 12 13]


In [ ]:
a = np.array([2,4,6,8])
b = np.array([1,3,5,7])
print(a*b)
print(a+b)
print(a-b)
print(a/b)






[  4  24  60 112]
[ 3  7 11 15]
[1 1 1 1]
[2.         1.33333333 1.2        1.14285714]


In [ ]:
a = np.random.randint(2,15,6)
print(a)

b = a.reshape((2,3))
print(b)

c = np.transpose(b)
print(c)



[13 12  5  2 11  5]
[[13 12  5]
 [ 2 11  5]]
[[13  2]
 [12 11]
 [ 5  5]]


In [ ]:
a = np.random.randint(2,14,6)
b = np.random.randint(1,19,6)

c = np.where(b>2, b, a)
print(c)
print(a)
print(b)


print(np.concatenate((a,b)))






[10 12 17  5  7 13]
[ 5  6  2 11  8  6]
[10 12 17  5  7 13]
[ 5  6  2 11  8  6 10 12 17  5  7 13]


In [ ]:
a = np.random.randint(2,14,6)
b = np.random.randint(1,19,6)
a.sort()
b. sort()

print(a)
print(b)


[ 5  8  8 10 12 13]
[ 5  6  6  8 16 16]


In [ ]:



player_scores = [45, 66, 78, 93, 110, 200, 0]


print("Max:", np.max(player_scores))
print("Min:", np.min(player_scores))
print("Mean:", round(np.mean(player_scores), 2))
print("Sum:", np.sum(player_scores))
print("Sorted:", np.sort(player_scores))

Max: 200
Min: 0
Mean: 84.57
Sum: 592
Sorted: [  0  45  66  78  93 110 200]


In [ ]:


products = []
prices = []

n = int(input("Enter no. of products: "))

for i in range(n):
    product = input(f"Enter name of product {i+1}: ")
    price = float(input(f"Enter price of {product}: "))

    products.append(product)
    prices.append(price)

p = np.array(prices)

print("\nProducts and Prices:")
for i in range(n):
    print(products[i], ":", prices[i])

print("\nHighest Price:", p.max())
print("Lowest Price:", p.min())
print("Total Price:", p.sum())
print("Average Price:", p.mean())
print("Standard Deviation:", p.std())

KeyboardInterrupt: Interrupted by user

In [ ]:
import numpy as np

a = np.random.randint(1, 99, (5, 5))
print(a)

print("row means:", a.mean(axis=1))

print("column means:", a.mean(axis=0))

a[a % 2 == 0] = -1

a.sort(axis=1)
a.sort(axis=0)

b = a.sum(axis=1)
c = a.sum(axis=0)

d = np.count_nonzero(a == -1, axis = 0)

print(b)
print(c)
print(d)








[[15 65 44 68 36]
 [16 76 94 11 24]
 [62 70 52 61 24]
 [39  1 52 40 64]
 [ 1 48 11 68 19]]
row means: [45.6 44.2 53.8 39.2 29.4]
column means: [26.6 52.  50.6 49.6 33.4]
[ 7 15 37 69 79]
[ -5  -5  -3  25 195]
[5 5 4 2 0]


In [ ]:
a = np.random.randint(20, 80, (5, 5))  #a=stock
b = np.random.randint(20, 80, (5, 5))  #b=demand

#rem_stock
c = (a-b)
print(c)

i = np.where(c<0 , 0 , c)
print(i)

s = np.sum(c[c<0])
print(s)

i.sort(axis=0)


[[ -2 -25 -12 -22  -1]
 [  5 -47 -12  13 -13]
 [ 28 -21  11  -1 -19]
 [-38 -39  28 -20  31]
 [-31 -16  14 -28   7]]
[[ 0  0  0  0  0]
 [ 5  0  0 13  0]
 [28  0 11  0  0]
 [ 0  0 28  0 31]
 [ 0  0 14  0  7]]
-347


# **Pandas**

In [ ]:

import pandas as pd

dct = {
    'name' : ['Tom', 'Nick', 'Krish', 'Jack'],
    'age' : [20, 21, 19, 18],
    'roll' : [1,2,3,4]
}

df = pd.DataFrame(dct , index = ['a','b','c','d'])


df1 = pd.DataFrame(dct)

display(df)
display(df1)







In [36]:
df = pd.read_json('MOCK_DATA.json')

#df.head()
df.tail(5)
#df.info()
#df.describe()
#df.shape


df.columns



Index(['id', 'first_name', 'last_name', 'email', 'gender', 'ip_address'], dtype='object')

In [83]:
df = pd.read_csv('student_data.csv')
# df.tail(3)

# df[['study_hours', 'internet_usage']]

# df.loc[df['assignments_completed'] == 8].iloc[:, 1]

df[df["assignments_completed"]> 3]

# df["new_column"] = value

# df["age"] = 20
# df

# remane the column
#inplace used to change in current data

# df.rename(columns = {'assignments_completed': 'assign_compleeted'}, inplace=True)

# df= df.rename(columns = {'assignments_completed': 'assign_compleeted'})
# df

# df.columns

# Drop a single column
# df.drop(columns='internet_usage', axis=0)

# df.drop([1] , axis=1)









,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
